name: 'Anchore Container Vulnerability Scan'

on:
  workflow_call:
    inputs:
      severity-cutoff:
        required: false
        type: string
        default: "high"
      fail-build:
        required: false
        type: boolean
        default: false
      output-format:
        required: false
        type: string
        default: "table"
      docker-compose-file:
        required: false
        type: string
        default: ""
      dockerfile-dir:
        required: false
        type: string
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2

      - name: Build dockerfile
        if: ${{ inputs.dockerfile-dir != '' }}
        run: docker build ${{ inputs.dockerfile-dir }} --file Dockerfile --tag localbuild/testimage:latest
        shell: bash
      
      - uses: anchore/scan-action@v3
        if: ${{ inputs.dockerfile-dir != '' }}
        with:
          image: "localbuild/testimage:latest"
          fail-build: ${{ inputs.fail-build }}
          severity-cutoff: ${{ inputs.severity-cutoff }}
          output-format: ${{ inputs.output-format }}

      - name: Run docker-compose
        if: ${{ inputs.docker-compose-file != '' }}
        run: docker-compose build -f ${{ inputs.docker-compose-file}}
        shell: bash

      - name: Get images
        if: ${{ inputs.docker-compose-file != '' }}
        run: |
          docker images > images.txt

          input=images.txt

          while IFS= read -r line
          do
              read -a arr <<< $line
              REPO_NAME=${arr[0]}

              if [[ "$REPO_NAME" != "REPOSITORY" ]]; then
                  TAG=${arr[1]}
                  IMAGE_NAME="$REPO_NAME:$TAG"
                  echo $IMAGE_NAME
              fi

          done < "$input"
        shell: bash
