name: 'Anchore Container Vulnerability Scan'

on:
  workflow_call:
    inputs:
      severity-cutoff:
        required: false
        type: string
        default: "high"
      fail-build:
        required: false
        type: boolean
        default: false
      output-format:
        required: false
        type: string
        default: "table"
      docker-compose-file:
        required: false
        type: string
        default: ""
      dockerfile-dir:
        required: false
        type: string
        default: ""

jobs:
  run:
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    outputs:
      images: ${{ steps.getimages.outputs.images }}
    steps:
      - uses: actions/checkout@v2

      - name: Build dockerfile
        if: ${{ inputs.dockerfile-dir != '' }}
        run: docker build ${{ inputs.dockerfile-dir }} --file Dockerfile --tag localbuild/testimage:latest
        shell: bash
      
      - uses: anchore/scan-action@v3
        if: ${{ inputs.dockerfile-dir != '' }}
        with:
          image: "localbuild/testimage:latest"
          fail-build: ${{ inputs.fail-build }}
          severity-cutoff: ${{ inputs.severity-cutoff }}
          output-format: ${{ inputs.output-format }}

      - name: Run docker-compose
        if: ${{ inputs.docker-compose-file != '' }}
        run: docker-compose -f ${{ inputs.docker-compose-file}} build
        shell: bash

      - name: Get images
        id: getimages
        if: ${{ inputs.docker-compose-file != '' }}
        run: |
          docker images > images.txt

          imagesArray=()

          input=images.txt

          while IFS= read -r line
          do
              read -a arr <<< $line
              REPO_NAME=${arr[0]}

              if [[ "$REPO_NAME" != "REPOSITORY" ]]; then
                  TAG=${arr[1]}
                  IMAGE_NAME="$REPO_NAME:$TAG"

                  if [[ $IMAGE_NAME = ${{ github.event.repository.name }}* ]]
                  then
                    echo "Image $IMAGE_NAME found."
                    imagesArray+=($IMAGE_NAME)
                  fi

              fi

          done < "$input"

          echo "images=${imagesArray[@]}" >> $GITHUB_OUTPUT
        shell: bash

  run-with-docker-compose:
    needs: [ run ]
    runs-on: ubuntu-latest
    if: ${{ inputs.docker-compose-file != '' }}
    steps:
      - run: |
          echo "this is env ${{ needs.run.outputs.images }}"
          echo "this is matrix ${{toJSON(needs.run.outputs.images)}} "
