name: 'Dependency License Check'

on:
  workflow_call:
    inputs:
      dependency-check-config-file:
        required: true
        type: string
        default: "dependency-check-config.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    # this job depends on github.head_ref, only available for pull_request/pull_request_target
    if: github.actor != 'dependabot[bot]' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/stefanzweifel/git-auto-commit-action/blob/master/README.md#example-workflow
          ref: ${{ github.head_ref }}

      - name: Checkout dependency license check repository
        uses: actions/checkout@v3
        with:
          repository: chronograph-pe/dependency-track-gh-action
          ref: main
          path: dependency-track-gh-action

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Run dependency license check
        env:
          DEPENDENCY_CHECK_CONFIG: ${{ inputs.dependency-check-config-file }}
        run: |
            pip install -r dependency-track-gh-action/requirements.txt
            python dependency-track-gh-action/app/main.py
            cat /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/job_summary.md >> $GITHUB_STEP_SUMMARY
            rm -rf dependency-track-gh-action
            rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/job_summary.md

      - name: Commit license data to this branch
        uses: stefanzweifel/git-auto-commit-action@v4
        
