name: 'Semgrep SAST Scan'

on:
  workflow_call:
    inputs:
      semgrep-scan-timeout:
        required: false
        type: string
        default: 300
    secrets:
      semgrep-app-token:
        required: true
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: github.actor != 'dependabot[bot]' && (github.event_name == 'pull_request' || github.event_name == 'pull_request_target')
    steps:
      - uses: chronograph-pe/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
        continue-on-error: true
        with:
          egress-policy: audit
      - run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - uses: chronograph-pe/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: semgrep ci || true
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.semgrep-app-token }}
          SEMGREP_TIMEOUT: ${{ secrets.semgrep-scan-timeout }}
